### ISSUE TITLE
Negative(or 0) room capacity other than -1

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#1]
Summary: The room capacity when adding a room can be a negative number or 0.

Attempt: When I attempted to add a room using addRoom() I was able to add a negative number as the room's capacity, except for -1. I was also able to give it the capacity of 0. 

Expected result: The expected result would be to not allow me to create a room with a negative capacity or 0.

Actual Result: A room was created with an invalid room capacity.

Environment: Windows 10, commit id  d35f2db, commited on 2/20/17

Steps to reproduce: Press 1 on main menu to add a room. Type in a room name. Enter in a negative number other than -1.

**Comment by elliottpicker** [comment]
Corrected

addRoomMethod now considers capacity < 0 invalid
