### ISSUE TITLE
Duplicate room names allowed

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#10]
Summary: You can create rooms with the same room name

Attempt: I went to create a room with the name 'test'. I then created another room with the name 'test'. There were then two rooms named 'test'.

Expected result: I would expect the program to have unique room names, and not allow duplicate room names.

Actual Result: Two rooms with the same name were created.

Environment: Windows 10, commit id d35f2db, committed on 2/20/17

Steps to reproduce: Create a room by selecting the first option in the main menu. Enter any name when prompted for a room name. Create another room with the same name as the first room you created.

**Comment by elliottpicker** [comment]
Corrected so that duplicate room names will not be allowed

addRoom method now checks to ensure the enterred room name does not already exist
