### ISSUE TITLE
Importing json file not in json format crashes the program

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#2]
Summary: Importing a file name "roomscheduler.json" that is not in json format will cause the program to crash

Attempt: I attempted to import a file using importRoomData() with a roomscheduler.json file that I created that was not in json format.

Expected result: I would expect for it to not allow me to import a json file that is not in json format, and display an error to the console but not crash the system.

Actual Result: The program crashed

Environment: Windows 10, commit id d35f2db, commited on 2/20/17

Steps to reproduce: Create a file name roomscheduler.json in the appropriate location. Typing random characters and numbers into the file. Import the file by pressing 6 in the main menu.

**Comment by elliottpicker** [comment]
fixed

adjusted importRoomData to soft fail on any exception rather than just i/o
