### ISSUE TITLE
Able to schedule a meeting in the past

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#3]
Summary: It is possible to schedule a meeting with a start and end date that happened in the past.

Attempt: I attempted to schedule a meeting for a room with a start and end date in the year 2016.

Expected result: I would expect for it to not allow me to create a meeting with a past date.

Actual Result: I created a meeting with a past date.

Environment: Windows 10, commit id d35f2db, committed on 2/20/17

Steps to reproduce: Create room using the first option on the main menu. Schedule a meeting for that room by pressing 3 in the main menu. Insert any date for start or end date that occurred before present day.

**Comment by elliottpicker** [comment]
fixed with _Meetings can be scheduled 1000 years in the future #6_

> 
Adjusted scheduleRoom method to ensure that start and end date are within this millennium (today-2999)
