### ISSUE TITLE
Meetings can last multiple days

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#4]
Summary: You can schedule a meeting that lasts more the one day

Attempt: I attempted to schedule a meeting that started on one day and ended on the day after that. This could also be done with any amount of days.

Expected result: I would expect for it to not allow me to create a meeting that would last that long

Actual Result: I created a meeting that lasted more than day

Environment: Windows 10, commit id d35f2db, committed on 2/20/17

Steps to reproduce: Create room using the first option on the main menu. Schedule a meeting for that room by pressing 3 in the main menu. Insert any date for the start date and enter a date that occurs multiple days after the start date for the end date.

**Comment by elliottpicker** [comment]
working as designed

there may be scenarios where a group needs exclusive access to a room and may reserve the room for weeks
