### ISSUE TITLE
Meetings can be 0 minutes long

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#5]
Summary: You can schedule a meeting that lasts 0 minutes

Attempt: I attempted to schedule a meeting that started at 5:00 on a certain day and ended at 5:00 on the same day

Expected result: I would expect for it to not allow me to create a meeting that lasts 0 minutes

Actual Result: I created a meeting that lasts 0 minutes

Environment: Windows 10, commit id d35f2db, committed on 2/20/17

Steps to reproduce: Create room using the first option on the main menu. Schedule a meeting for that room by pressing 3 in the main menu. Insert any date for the start date at any time and then use that same time and date for the end date.

**Comment by elliottpicker** [comment]
fixed

scheduleMeeting now ensures that meetings are at least 5 minutes in duration
