### ISSUE TITLE
Meetings can be scheduled 1000 years in the future

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#6]
Summary: You can schedule a meeting that exists so far in the future that the program would have no relevance when that time comes.

Attempt: I attempted to schedule a meeting that started in the year 3000

Expected result: I would expect for it to not allow me to create a meeting that far into the future

Actual Result: I created a meeting the starts in the year 3000

Environment: Windows 10, commit id d35f2db, committed on 2/20/17

Steps to reproduce: Create room using the first option on the main menu. Schedule a meeting for that room by pressing 3 in the main menu. Insert 3000 for the year for the start date, then finish making the meeting.

**Comment by elliottpicker** [comment]
Solved

Adjusted scheduleRoom method to ensure that start and end date are within this millennium (2000-2999)
