### ISSUE TITLE
Error is display when I enter a valid date and time for a meeting if I previously entered an incorrect date/time

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#7]
Summary: If I type in an incorrect timestamp format, then enter a correct format afterwards, an exception error still gets logged to the console.

Attempt: I entered an invalid date for the start date, so it looped back to the beginning. After that I entered a valid start date, and an error was logged to the console. But, I was still able to create a valid meeting

Expected result: I would expect the error to be logged when I type in the incorrect format the first time, and I would not expect for it to show an error after I entered the correct format.

Actual Result: An error was logged to the console after I entered the correct format

Environment: Windows 10, commit id d35f2db, committed on 2/20/17

Steps to reproduce: Create room using the first option on the main menu. Schedule a meeting for that room by pressing 3 in the main menu. Enter an invalid date for the start date. When prompted again, input a valid date. An error then gets displayed, but you can still finish making the meeting.

**Comment by elliottpicker** [comment]
Unable to reproduce.

I believe this may have been fixed during earlier refactoring as part of incorporating log4j
