### ISSUE TITLE
Adding a room doesn't handle room name with spaces well

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#8]
Summary: Entering a room name, when adding a new room, with multiple spaces causes “invalid room capacity enterredjava.util.InputMismatchException” to be logged to the console for every space entered

Attempt: I went to create a new room, and for the room name I input a name that had multiple spaces in it. This caused a java exception to be logged for every space in the name

Expected result: I would expect the program to handle spaces in the name correctly, and not overflow into the capacity field.

Actual Result: An exception was logged for every space in the room name that I entered

Environment: Windows 10, commit id d35f2db, committed on 2/20/17

Steps to reproduce: Create room using the first option on the main menu. When prompted for a room name, enter a name that has multiple spaces in it.

**Comment by elliottpicker** [comment]
Identified source of bug and corrected in commit 756615c2d9484bf7715ecb7be3756d7e9e06c518

getRoomName method fixed to read in multiple words until end of line character as a room name
