### ISSUE TITLE
Removing a room name/scheduling a meeting for a room with multiple spaces in the name is not handled well.

### ISSUE THREAD

**Issue by gin-nader** [elliottpicker/MSCS721-roomScheduler#9]
Summary: If I try to delete a made up room with multiple spaces in it, “Unrecognized command, Please enter a menu option 1-8” shows up on the console along with the main menu for every space entered. This also happens when adding a schedule to a room.

Attempt: I went to delete a room/schedule a meeting for a room where the room name has multiple spaces in it. I get an error and the main menu is displayed for every space in the room name.

Expected result: I would expect the program to handle spaces in the name correctly, and not overflow into other blocks of code.

Actual Result: An error along with the main menu was displayed for each space in the room name.

Environment: Windows 10, commit id d35f2db, committed on 2/20/17

Steps to reproduce: Choose to remove a room/schedule a meeting from the main menu. Then input a name that has multiple spaces in it for the room name.

**Comment by elliottpicker** [comment]
same problem as _Adding a room doesn't handle room name with spaces well #8_

fixed by the change to getRoomName
